### ISSUE TITLE
PJLink stuck functions

### ISSUE THREAD

**Issue by scroix** [museumsvictoria/nodel-recipes#10]
Recently rolled out the new PJ-Link recipe.

I've noticed a rapid increase in **stuck functions**. The only solution is to restart the instance of Nodel, but the problem seems to reoccur not long afterwards.

```
04-10 12:04:06.31 These functions are stuck - local_action_GetPower_673 (1d 3h ago)
04-10 12:05:06.31 These functions are stuck - local_action_GetPower_673 (1d 3h ago)
```

**Comment by justparking** [comment]
(This is related to #13 and will be discussed there.)
