### ISSUE TITLE
Recipe Sync Error

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel-recipes#11]
If you copy a recipe sync recipe into a node folder, you immediately get errors in the main Nodel Diagnostics, and sometimes the nodelhost becomes unresponsive.

'''[nodeloneoff_14] [org.nodel.jyhost.PyNode_13_testNodelRecipeSync] The bindings could not be applied to the Python instance. Traceback (most recent call last):
      File "C:\Nodel\.\nodes\testNodel Recipe Sync\script.py", line 19, in <module>
        from org.eclipse.jgit.api import Git
    ImportError: No module named eclipse
'''

I presume its not gracefully failing the check for the eclipse module.  should we be checking if the module exists before importing it so it can gracefuly error out. and have a note in the recipe stating where and how to get eclipse?

**Comment by scienceworld** [comment]
Requires rev315 or higher

**Comment by justparking** [comment]
... currently [nodelhost-dev-2.1.1-rev319c.jar](https://github.com/museumsvictoria/nodel/releases) or later. Closing issue.
