### ISSUE TITLE
advschedule gui issue

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel-recipes#12]
after updating nodel host to rev300 or higher advscheduler nodes no longer display a gui.
<img width="716" alt="screen shot 2017-05-01 at 10 18 05 pm" src="https://cloud.githubusercontent.com/assets/3997916/25604893/10af51a2-2ebc-11e7-8be7-39ac5d1633f3.png">

**Comment by mcartmel** [comment]
The custom html is missing some references to required JS libraries. Added now.
