### ISSUE TITLE
Support for momentary buttons in frontend recipe

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel-recipes#17]
(shifted from https://github.com/museumsvictoria/nodel/issues/105)

**Comment by mcartmel** [comment]
Closing as this was addressed previously. Momentary buttons can be specified by adding `type='momentary'` to the button tag (see example).

**Comment by mcartmel** [comment]
Apologies, re-opening as there is still an outstanding task to update the XML parser to automatically generate actions for "action-on" and "action-off".

**Comment by justparking** [comment]
There's an issue here: `-off` actions doesn't fire.

Example:
```xml
<button type="momentary" action-off='VolumeStop' action-on='VolumeDownOn' class='btn-success'>Down</button>
```

```python
@after_main
def custom():
  lookup_local_action('VolumeDownOn').addCallHandler(lambda arg: console.info('Down On!'))
  lookup_local_action('VolumeStop').addCallHandler(lambda arg: console.info('Stop!'))
```

Then when using browser, only get this:

```log
07-26 20:42:48.38 Down On!
07-26 20:42:48.42 Down On!
```

And have confirmed through Chrome only the `VolumeDownOn` is being called.

**Comment by mcartmel** [comment]
Fixed in latest commit
