### ISSUE TITLE
Excahange Recipe failed

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel-recipes#18]
Today we had a failure of the exchange recipe, it no longer connected to exchange.  We had to re-start the nodel host to get it working again.

it said something like the calendar couldnt be found.  I didnt save the console before restarting so I can't paste the exact error.

**Comment by scienceworld** [comment]
Happened again.  restarting nodel did not fix the issue, dead in the water at the moment.


console log
`06-16 08:25:03.69 Action call failed - Traceback (most recent call last):
06-16 08:25:03.69   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 146, in local_action_PollItems
06-16 08:25:03.69     rawBookings = query_ews(now, now.plusDays(7))
06-16 08:25:03.69   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 235, in query_ews
06-16 08:25:03.69     items = parse_query_response(response, warnings)
06-16 08:25:03.69   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 286, in parse_query_response
06-16 08:25:03.69     subject = getElementText(item, 'type:Subject')
06-16 08:25:03.69   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 552, in getElementText
06-16 08:25:03.69     raise DataException('Missing element %s' % path)
06-16 08:25:03.69 __builtin__.DataException: Missing element type:Subject
06-16 08:25:03.69 
06-16 08:25:03.73 (timer) Traceback (most recent call last):
06-16 08:25:03.73   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 141, in <lambda>
06-16 08:25:03.73     timer_poller = Timer(lambda: lookup_local_action('PollItems').call(), 10, 10)
06-16 08:25:03.73   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 146, in local_action_PollItems
06-16 08:25:03.73     rawBookings = query_ews(now, now.plusDays(7))
06-16 08:25:03.73   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 235, in query_ews
06-16 08:25:03.73     items = parse_query_response(response, warnings)
06-16 08:25:03.73   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 286, in parse_query_response
06-16 08:25:03.73     subject = getElementText(item, 'type:Subject')
06-16 08:25:03.73   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 552, in getElementText
06-16 08:25:03.73     raise DataException('Missing element %s' % path)
06-16 08:25:03.73 __builtin__.DataException: Missing element type:Subject
06-16 08:25:03.73 	at org.nodel.jyhost.PyNode.handleActionRequest(PyNode.java:990)
06-16 08:25:03.73 	at org.nodel.jyhost.PyNode$11.handleActionRequest(PyNode.java:919)
06-16 08:25:03.73 	at org.nodel.core.NodelServerAction$1.handleActionRequest(NodelServerAction.java:240)
06-16 08:25:03.73 	at org.nodel.core.NodelServerAction.call(NodelServerAction.java:265)
06-16 08:25:03.73 	at org.nodel.core.NodelServerAction.call(NodelServerAction.java:259)
06-16 08:25:03.73 	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
06-16 08:25:03.73 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
06-16 08:25:03.73 	at java.lang.reflect.Method.invoke(Unknown Source)
06-16 08:25:03.73 java.lang.RuntimeException: java.lang.RuntimeException: Traceback (most recent call last):
06-16 08:25:03.73   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 146, in local_action_PollItems
06-16 08:25:03.73     rawBookings = query_ews(now, now.plusDays(7))
06-16 08:25:03.73   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 235, in query_ews
06-16 08:25:03.73     items = parse_query_response(response, warnings)
06-16 08:25:03.73   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 286, in parse_query_response
06-16 08:25:03.73     subject = getElementText(item, 'type:Subject')
06-16 08:25:03.73   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 552, in getElementText
06-16 08:25:03.73     raise DataException('Missing element %s' % path)
06-16 08:25:03.73 __builtin__.DataException: Missing element type:Subject`

error dialogue
`exec - Error: error {"cause":{"error":"PyException","message":"Traceback (most recent call last):\r\n File \"C:\\Nodel\\.\\nodes\\System - Microsoft Exchange Scheduler Retriever\\script.py\", line 146, in local_action_PollItems\r\n rawBookings = query_ews(now, now.plusDays(7))\r\n File \"C:\\Nodel\\.\\nodes\\System - Microsoft Exchange Scheduler Retriever\\script.py\", line 235, in query_ews\r\n items = parse_query_response(response, warnings)\r\n File \"C:\\Nodel\\.\\nodes\\System - Microsoft Exchange Scheduler Retriever\\script.py\", line 286, in parse_query_response\r\n subject = getElementText(item, 'type:Subject')\r\n File \"C:\\Nodel\\.\\nodes\\System - Microsoft Exchange Scheduler Retriever\\script.py\", line 552, in getElementText\r\n raise DataException('Missing element %s' % path)\r\n__builtin__.DataException: Missing element type:Subject\r\n"},"error":"RuntimeException","message":"Traceback (most recent call last):\r\n File \"C:\\Nodel\\.\\nodes\\System - Microsoft Exchange Scheduler Retriever\\script.py\", line 146, in local_action_PollItems\r\n rawBookings = query_ews(now, now.plusDays(7))\r\n File \"C:\\Nodel\\.\\nodes\\System - Microsoft Exchange Scheduler Retriever\\script.py\", line 235, in query_ews\r\n items = parse_query_response(response, warnings)\r\n File \"C:\\Nodel\\.\\nodes\\System - Microsoft Exchange Scheduler Retriever\\script.py\", line 286, in parse_query_response\r\n subject = getElementText(item, 'type:Subject')\r\n File \"C:\\Nodel\\.\\nodes\\System - Microsoft Exchange Scheduler Retriever\\script.py\", line 552, in getElementText\r\n raise DataException('Missing element %s' % path)\r\n__builtin__.DataException: Missing element type:Subject\r\n"}
Nodel
System - Microsoft Exchange Scheduler Retriever
Advanced mode
 Enabled
Actions
`

**Comment by scienceworld** [comment]
Found the problem for this latest occurance.

A future dated calendar entry (within the 7 day outlook of events to be downloaded) was missing a calendar Title.  The exchange calendar node failed to validate which resulting in it not downloading any new or updated entries until the title was filled in.

Please introduce some error checking that allows it to either operate without a title, or to ignore an entry without a title and continue to download and parse other events.

![image](https://user-images.githubusercontent.com/3997916/27233926-128bdd88-5270-11e7-9962-b2952822df0a.png)

**Comment by justparking** [comment]
I've addressed most of these issues in recent commit 8478861bd04edf798484ce00c525a30fd068492f including:
* 'status' support when a full poll-cycles continually fail
   * Note: this is generally a good catch-all for most critical conditions including permanent network issues, authentication, etc., but at the same time it doesn't catch intermittent failures that can often occur with high-level network protocols, esp. of the Internet (e.g. the odd timeout)

* extended the optional field set ('subject', 'sensitivity', 'organiser')
* console tidy-up (can still use 'trace' signal for protocol dumps)

@scienceworld Feel free to update and "wire" the **status** signal into your system. We generally use an **Infrastructure** group node to aggregate statuses.
