### ISSUE TITLE
pjlink error sony vpl-fhz55

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel-recipes#20]
New pjlink node created for sonly vpl-fhz55
used latest pjlink from git repo

upon entering correct port, password and ip address getting script errors and communication timeout.

![image](https://user-images.githubusercontent.com/3997916/31139680-237ee646-a827-11e7-9061-5082782f8925.png)

**Comment by justparking** [comment]
This condition only occurs on the very first time the recipe runs because the "Errors" signal is not seeded.

I've updated the recipe to look out for that.

**Comment by justparking** [comment]
from previous comment, see 462bee7ada488f07377b29f5c15a9905e8dfd588.
