### ISSUE TITLE
Microsoft Exchange schedule retriever: console reports "Anonymous Request Disallowed"

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel-recipes#25]
Some internally hosted versions of Exchange are reporting: "Anonymous Request Disallowed".

**Comment by scroix** [comment]
Updated to [r338](https://github.com/museumsvictoria/nodel/commit/3d6f25a4592ad60131509ecb075b8897b3241375) and the retriever appears to be working - no errors reported.

However, the node host console is reporting the same message as prior to the update.
```
02-19 14:51:47.06 err: Feb 19, 2018 2:51:47 PM org.apache.http.impl.auth.HttpAuthenticator generateAuthResponse
02-19 14:51:47.06 err: WARNING: NEGOTIATE authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
```

**Comment by justparking** [comment]
OK, sounds like it's working. You can ignore those warnings. They come from the HTTP module (this issue all happens to covers that: https://github.com/museumsvictoria/nodel/issues/88).

Future releases of Nodel should ideally have that suppressed or at least those logs routed through to the related node's console.

NOTE: I'll keep this issue open until the release of Nodel is uploaded to **/releases**.

**Comment by justparking** [comment]
Pushed release https://github.com/museumsvictoria/nodel/releases/tag/v2.1.1_dev_rev341

That stray logging should be suppressed now too.
