### ISSUE TITLE
Front-end: Some URL-encoded characters cause display failure

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel-recipes#28]
To replicate, set up a Front-end node, for example: **SW-BPAM02 (XMV8280-D Rack 1)**

1: `http://localhost:8085/nodes/SW-BPAM02%20(XMV8280-D%20Rack%201)/index-sample.xml` works correctly:
![image](https://user-images.githubusercontent.com/5266533/39555700-a9879704-4ebe-11e8-9ea1-e079221085ef.png)

2: `http://localhost:8085/nodes/SW-BPAM02%20%28XMV8280-D%20Rack%201%29/index-sample.xml` does **NOT** (blank page):
![image](https://user-images.githubusercontent.com/5266533/39555752-ed3fd1fa-4ebe-11e8-8411-d47c7e63edc7.png)

In this example, it's the `()` being encoded as `%28%29` respectively, however this may highlight some kind of general escaping issue.

This is an issue because many of the Nodel browsers redirect the user to the encoded version (2).

**Comment by scroix** [comment]
This was addressed a while back. I can't recall exactly which PR, but the extraneous names in "( )" etc are ignored in the URLs now.

e.g. `SW-BPAM02 (XMV8280-D Rack 1)` would appear as `(http://localhost:8085/nodes/SWBPAM02/index.xml)`
