### ISSUE TITLE
Yamaha XMV: Frontend dependencies missing

### ISSUE THREAD

**Issue by scroix** [museumsvictoria/nodel-recipes#34]
The recipe is "installed" with `custom/frontend.xml` however the rest of the dependencies (shown below) aren't present.

![dependencies](https://user-images.githubusercontent.com/9277107/50124787-40739500-02ba-11e9-9a65-cd8759fac1c0.PNG)

This can be worked-around by copying the dependencies from the **Frontend** recipe and locating them in either the `node_host/nodes/node_name/custom` folder or more conveniently the nodehost's `node_host/custom/content` folder, which will be available to all nodes.

I'd suggest that in the long term either support for these frontends could be baked into nodel-core or introducing documentation to better explain this process.

**Comment by mcartmel** [comment]
Closing this issue. Please follow museumsvictoria/nodel#123 for updates.
