### ISSUE TITLE
Yamaha XMV: IPAddress Recipe error

### ISSUE THREAD

**Issue by nodel** [museumsvictoria/nodel-recipes#36]
I get a **NameError: global name 'is_blank' is not defined** when entering an IP address or hostname into the IP address field on new nodel instances of the Yamaha XMV recipe.

I then get a tcp_timeout,  even when I copy the hostname from a currently operational XMV node. 

03-27 09:11:13.65 (Python and Node script loaded in 217ms; calling 'main'...)
03-27 09:11:13.65 'main' completed with errors - Traceback (most recent call last):
03-27 09:11:13.65   File "<string>", line 1, in <module>
03-27 09:11:13.65   File "\nodes\xmv-amp\script.py", line 137, in main
03-27 09:11:13.65     if is_blank(param_IPAddress):
03-27 09:11:13.65 NameError: global name 'is_blank' is not defined
03-27 09:11:13.65 
03-27 09:11:44.66 tcp_timeout
03-27 09:12:00.68 tcp_timeout
03-27 09:12:16.69 tcp_timeout

**Comment by scroix** [comment]
Is the problematic node running on a different nodehost, and if so, which version of Nodel are you running?

The `is_blank` function used by the Yamaha XMV Recipe wasn't introduced until [rev.352](https://github.com/museumsvictoria/nodel/releases/tag/v2.1.1_dev_rev352).

**Comment by nodel** [comment]
Ahhh - 2.1.1-release_r330

**Comment by nodel** [comment]
Moved to a 2.1.1-dev_r379 and it works! thanks @scriox

**Comment by scroix** [comment]
No problem. Good luck.
