### ISSUE TITLE
Advanced Schedule recipe not showing cron description

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel-recipes#4]
The cron description is now missing since the upgrade to nodel 2.1.1.  This might be Jquery related.

![image](https://cloud.githubusercontent.com/assets/3997916/12868590/35e576ba-ccbe-11e5-9140-fceaef8d4151.png)

If you press the Add button the descriptions show up

![image](https://cloud.githubusercontent.com/assets/3997916/12868594/4f0723a0-ccbe-11e5-8a92-8fd2a9becc70.png)

**Comment by scienceworld** [comment]
any chance this could be fixed?

**Comment by scienceworld** [comment]
would still like to get this fixed.  difficult being able to see the expression the cron syntax to verify you got it right.

**Comment by mcartmel** [comment]
This seems to be working now?

**Comment by scienceworld** [comment]
Yes it does.  Thank you.

On May 1, 2017, at 11:22 PM, mcartmel <notifications@github.com<mailto:notifications@github.com>> wrote:


This seems to be working now?

**Comment by mcartmel** [comment]
Closing
