### ISSUE TITLE
Computer Controller: gracefully show screenshot errors

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel-recipes#51]
I've noticed that if a screenshot cannot be captured the process simply dies, say when workstation is locked.

Gracefully handling that condition with a static "UNAVAILABLE" PNG would be ideal.

**Comment by scroix** [comment]
This was addressed way back in https://github.com/museumsvictoria/nodel-recipes/pull/49

_Case closed_ 🙇
