### ISSUE TITLE
EWS decommissioning - Microsoft Exchange schedule retriever

### ISSUE THREAD

**Issue by robbie-brown** [museumsvictoria/nodel-recipes#56]
https://techcommunity.microsoft.com/t5/exchange-team-blog/upcoming-changes-to-exchange-web-services-ews-api-for-office-365/ba-p/608055

Hey team, while trying (and failing) to set up Microsoft Exchange node I came across this article stating that EWS will be decommisoned as of 13th Oct 2020 (maybe later). I know the recipe relys on the EWS API. Wondering if there will be a new release addressing this issue? Looks like my organisation has already moved away from EWS in favour of other types of auth hence my issues with set-up. 

Thanks,
RB

**Comment by paxofsnax** [comment]
looks like i may have just run into this problem

**Comment by paxofsnax** [comment]
FYI moved from on-prem to office 365 and used this address with the same recipe. works.
https://outlook.office365.com/EWS/Exchange.asmx
--

**Comment by paxofsnax** [comment]
So as of November 12/11/2020 Basic Authentication for EWS to access Exchange Online is still working but it looks like it may be decommissioned for OAuth 2.0 for authentication - EWS will continue to work.
