### ISSUE TITLE
Computer Controller: failures when no audio devices present

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel-recipes#61]
When no audio devices are present on a system the ComputerController.exe fails.

It needs to handle graceful changes in hardware over time.

**Comment by morimoriysmoon** [comment]
The recipe updated to check if audio devices exist.
9f01480f0cec6790d436d0940884d0511d007b57

**Comment by justparking** [comment]
Hey @morimoriysmoon , I meant to indicate this was actually related to the _Windows_ Computer Controller [recipe](https://github.com/museumsvictoria/nodel-recipes/tree/master/Computer%20Controller/Windows%2010).

**Comment by morimoriysmoon** [comment]
fixed https://github.com/museumsvictoria/nodel-recipes/pull/63

**Comment by justparking** [comment]
I did something similar except added graceful shutdown if the audio goes missing or changes.
