### ISSUE TITLE
Calendar: "Momentary" events can sometimes be missed (endtime strictly equals starttime)

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel-recipes#65]
_Discovered and reported by @dargs, [ACMI](https://acmi.net.au/)_

It's possible that over time the calendar node can miss the firing of momentary events.

Having a look at the code I can see where a related bug might exist which could cause a race condition.

NOTE: _only_ momentary events are affected which was the feature most recently added to the calendar node. 

Normal events are not affected i.e. those that have a duration (starttime ≠ endtime)

I'll put out a bugfix very soon...

**Comment by justparking** [comment]
An update is ready to be tested. Covered https://github.com/museumsvictoria/nodel-recipes/pull/67

**Comment by scroix** [comment]
Closing this issue based on the assumption that this issue has been addressed by https://github.com/museumsvictoria/nodel-recipes/pull/67 which was recently merged.
